export const env = {
    CLOUD_NAME: process.env.EXPO_PUBLIC_CLOUD_NAME,
    CLOUDINARY_ENDPOINT: process.env.EXPO_PUBLIC_CLOUDINARY_ENDPOINT,
    CLOUDINARY_KEY: process.env.EXPO_PUBLIC_CLOUDINARY_API_KEY
}